<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="PresentationFramework" />
    <Reference Include="PresentationCore" />
    <Reference Include="WindowsBase" />
    <Reference Include="System.Xaml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AvalonEdit" Version="6.3.0.90" />
    <PackageReference Include="DiffPlex" Version="1.7.2" />
    <PackageReference Include="Microsoft.VisualStudio.Shell.15.0" Version="17.14.40264" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DBVC.Core\DBVC.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="source.extension.vsixmanifest" />
  </ItemGroup>

</Project>
